on:
  pull_request: []

jobs:
  slack-poster:
    runs-on: ubuntu-latest
    name: Run Jobs Slack Poster
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: updater
        name: Job Updater
        uses: ./
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          filename: "example/jobs.yaml"
          previous_filename: "example/jobs-previous.yaml"
          keys: "url"
          unique: "url"

          deploy: false
          test: true

          # Also deploy to Mastodon (all secrets required in repository secrets)
          mastodon_deploy: false
          mastodon_access_token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          mastodon_api_base_url: ${{ secrets.MASTODON_API_BASE_URL }}

      - id: multifield_updater
        name: Job Updater
        uses: ./
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          filename: "example/jobs.yaml"
          previous_filename: "example/jobs-previous.yaml"
          keys: "name,location,url"
          unique: "url"

          deploy: false
          test: true

      - run: echo ${{ steps.updater.outputs.fields }}
        name: Show Keys Used
        shell: bash
        
      - run: echo ${{ steps.updater.outputs.matrix }}
        name: Show Matrix
        shell: bash
