on:
  push:
    paths:
      - 'example/jobs.yaml'
    branches:
      - main

jobs:
  slack-poster:
    runs-on: ubuntu-latest
    name: Run Jobs Slack Poster
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - id: updater
        name: Job Updater
        uses: ./
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          filename: "example/jobs.yaml"
          key: "url"
          deploy: false
          test: false

          # Also deploy to Twitter (all secrets required in repository secrets)
          mastodon_deploy: true
          mastodon_access_token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          mastodon_api_base_url: ${{ secrets.MASTODON_API_BASE_URL }}

      - run: echo ${{ steps.updater.outputs.fields }}
        name: Show New Jobs
        shell: bash
